//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANGPHANCONGVESINH
    {
        public string MaVeSinh { get; set; }
        public string MaNhanVien { get; set; }
        public string MaChuong { get; set; }
        public string TenVeSinh { get; set; }
        public System.DateTime NgayLam { get; set; }
    
        public virtual CHUONG CHUONG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
