//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BENH
    {
        public BENH()
        {
            this.BANGDIEUTRIs = new HashSet<BANGDIEUTRI>();
        }
    
        public string MaBenh { get; set; }
        public string MaThuocDieuTri { get; set; }
        public string TenBenh { get; set; }
        public System.DateTime ThoiGianBenh { get; set; }
        public string TrieuChung { get; set; }
        public string TinhTrang { get; set; }
    
        public virtual ICollection<BANGDIEUTRI> BANGDIEUTRIs { get; set; }
        public virtual THUOCDIEUTRI THUOCDIEUTRI { get; set; }
    }
}
