//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONGVAT
    {
        public DONGVAT()
        {
            this.BANGDIEUTRIs = new HashSet<BANGDIEUTRI>();
            this.CHUONGs = new HashSet<CHUONG>();
            this.KHAUPHANANs = new HashSet<KHAUPHANAN>();
        }
    
        public string MaDongVat { get; set; }
        public string TenDongVat { get; set; }
        public string TenKhoaHoc { get; set; }
        public string GioiTinh { get; set; }
        public string Mau { get; set; }
        public Nullable<int> CanNang { get; set; }
        public Nullable<int> ChieuCao { get; set; }
        public Nullable<int> ChieuDai { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public System.DateTime NgayNhapVe { get; set; }
        public string Loai { get; set; }
        public string Chi { get; set; }
        public string Ho { get; set; }
        public string Bo { get; set; }
        public string Nganh { get; set; }
        public string SucKhoe { get; set; }
        public string HinhThucGiamSat { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string NoiXuatXu { get; set; }
        public string NoiCuTru { get; set; }
        public Nullable<int> TuoiTho { get; set; }
    
        public virtual ICollection<BANGDIEUTRI> BANGDIEUTRIs { get; set; }
        public virtual ICollection<CHUONG> CHUONGs { get; set; }
        public virtual ICollection<KHAUPHANAN> KHAUPHANANs { get; set; }
    }
}
