//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHAUPHANAN
    {
        public KHAUPHANAN()
        {
            this.BANGTHUCDONs = new HashSet<BANGTHUCDON>();
        }
    
        public string MaKhauPhanAn { get; set; }
        public string MaDongVat { get; set; }
        public string MaThucAn { get; set; }
        public int KhoiLuongKhauPhan { get; set; }
        public string ThoiGianAn { get; set; }
    
        public virtual ICollection<BANGTHUCDON> BANGTHUCDONs { get; set; }
        public virtual DONGVAT DONGVAT { get; set; }
        public virtual THUCAN THUCAN { get; set; }
    }
}
