//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLySoThuDbEntities : DbContext
    {
        public QuanLySoThuDbEntities()
            : base("name=QuanLySoThuDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACCOUNT> ACCOUNTs { get; set; }
        public DbSet<BANGDIEUTRI> BANGDIEUTRIs { get; set; }
        public DbSet<BANGPHANCONGVESINH> BANGPHANCONGVESINHs { get; set; }
        public DbSet<BANGTHUCDON> BANGTHUCDONs { get; set; }
        public DbSet<BENH> BENHs { get; set; }
        public DbSet<CHUONG> CHUONGs { get; set; }
        public DbSet<DONGVAT> DONGVATs { get; set; }
        public DbSet<KHAUPHANAN> KHAUPHANANs { get; set; }
        public DbSet<NHANVIEN> NHANVIENs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<THUCAN> THUCANs { get; set; }
        public DbSet<THUOCDIEUTRI> THUOCDIEUTRIs { get; set; }
    }
}
