//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class THUCAN
    {
        public THUCAN()
        {
            this.KHAUPHANANs = new HashSet<KHAUPHANAN>();
        }
    
        public string MaThucAn { get; set; }
        public string LoaiThucAn { get; set; }
        public string DonViTinh { get; set; }
        public string TenThucAn { get; set; }
        public int SoLuong { get; set; }
        public System.DateTime NgayNhap { get; set; }
        public string HamLuongDinhDuong { get; set; }
        public decimal GiaThanh { get; set; }
        public decimal ChiPhiVanChuyen { get; set; }
        public Nullable<decimal> PhatSinh { get; set; }
    
        public virtual ICollection<KHAUPHANAN> KHAUPHANANs { get; set; }
    }
}
