//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class THUOCDIEUTRI
    {
        public THUOCDIEUTRI()
        {
            this.BENHs = new HashSet<BENH>();
        }
    
        public string MaThuocDieuTri { get; set; }
        public string TenThuoc { get; set; }
        public int SoLo { get; set; }
        public Nullable<System.DateTime> NgaySanXuat { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        public int SoLuong { get; set; }
        public string DonViTinh { get; set; }
        public decimal DonGia { get; set; }
    
        public virtual ICollection<BENH> BENHs { get; set; }
    }
}
